version: '1.0'

services:
  db:
    image: timescale/timescaledb:2.11.0-pg15
    ports:
      - 7432:5432
    expose: 
      - 5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=amacast
      - TZ=Europe/Berlin

  analysis:
    build:
      context: ./analysis
      dockerfile: Dockerfile
    expose: 
      - 5000

  backend:
    build:
      context: ./amacast-server
      dockerfile: Dockerfile
    depends_on:
      - db
      - analysis
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=amacast
      - TZ=Europe/Berlin
      - ANALYSIS_HOST=http://analysis:5000
  
  frontend:
    build:
      context: ./amacast-frontend
      dockerfile: Dockerfile
    ports:
      - 7002:3000
