version: '1.0'

services:
  analysis:
    build:
      context: ./analysis
      dockerfile: Dockerfile
    expose: 
      - 5001
    ports:
      - 7001:5000

  db:
    image: timescale/timescaledb:2.11.0-pg15
    ports:
      - 7432:5432
    expose: 
      - 5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=amacast
      - TZ=Europe/Berlin
    volumes:
      - ./dumps/amacast_dump.sql:/docker-entrypoint-initdb.d/amacast_dump.sql:ro

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 7002:8080
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=user
      - DB_PASSWORD=pass
      - DB_NAME=amacast
      - TZ=Europe/Berlin
      - ANALYSIS_HOST=http://analysis:5000
  
  frontend:
    build:
      context: ./amacast-frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - 7003:3000

  data:
    build:
      context: .
      dockerfile: ./data-server/Dockerfile
    expose: 
      - 8080
    ports:
      - 7004:8080
