version: '2.2'

services:
  analysis:
    build:
      context: ./analysis
      dockerfile: Dockerfile
    restart: unless-stopped
    expose: 
      - 5000
      - 5001
    ports:
      - 7001:5000
    networks:
      - backend

  db:
    image: timescale/timescaledb:2.11.0-pg15
#    ports:
#      - 7432:5432
    expose: 
      - 5432
    restart: unless-stopped
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=amacast
      - TZ=Europe/Berlin
    volumes:
      - ./dumps/amacast_dump.sql:/docker-entrypoint-initdb.d/amacast_dump1.sql:ro
    networks:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
#    ports:
#      - 7002:8080
    depends_on:
      - db
    restart: unless-stopped
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=user
      - DB_PASSWORD=pass
      - DB_NAME=amacast
      - TZ=Europe/Berlin
      - ANALYSIS_HOST=http://analysis:5000
      - VIRTUAL_HOST=api.amacast.leoek.tech
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=api.amacast.leoek.tech
      - LETSENCRYPT_EMAIL=webmaster@leoek.tech
    networks:
      - backend
      - proxy-tier
  
  frontend:
    build:
      context: ./amacast-frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - backend
#    ports:
#      - 7003:3000
    environment:
      - VIRTUAL_HOST=amacast.leoek.tech
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=amacast.leoek.tech
      - LETSENCRYPT_EMAIL=webmaster@leoek.tech
    networks:
      - backend
      - proxy-tier

  data:
    build:
      context: .
      dockerfile: ./data-server/Dockerfile
    restart: unless-stopped
    expose: 
      - 8080
    ports:
      - 7004:8080
    networks:
      - backend
      - proxy-tier

networks:
  backend:
  proxy-tier:
    external:
      name: nginx-proxy